apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ../base/monitor/development
  - https://github.com/seanconroy2021/release-service/config/default?ref=3fa9f136cc152a14a95adf1deb239a381773ea9d
images:
  - name: quay.io/konflux-ci/release-service
    newName: quay.io/sconroykonflux/release-service
    newTag: next
namespace: release-service
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: controller-manager
    path: sealights-token-patch.yaml
